name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.1

      - name: Setup Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: "lts/*"

      - name: Setup environment
        run: |
          npm install -g corepack
          corepack enable
          corepack prepare

      - name: Setup
        run: |
          yarn install --immutable

      - name: Cache Next.js and OpenNext build
        uses: actions/cache@v5.0.1
        with:
          path: |
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/.open-next
          key: ${{ runner.os }}-nextjs-opennext-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-opennext-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-nextjs-opennext-

      - name: Build and Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          yarn deploy
